version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building application..."
      - mkdir output
      - cp index.html output/
artifacts:
  files:
    - output/*
